project:
  type: website
  output-dir: docs

website:
  title: "Simuluation Data Experiments"
  navbar:
    right:
      - testing.qmd
      - confidential.qmd
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    df-print: paged



